version: '3'

services:
  flask-services:
    build: ./flask
    links:
      - db
    volumes:
      - ./flask:/app
    ports:
      - 5000:5000
      - 5001:5001

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  # prometheus:
  #   image: prom/prometheus:v2.27.0
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   links:
  #     - flask-services
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:7.5.6
  #   environment: 
  #     GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
  #     GF_AUTH_ANONYMOUS_ENABLED: "true"
  #     GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  #     GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
  #     GF_AUTH_DISABLE_LOGIN_FORM: "true"
  #   volumes:
  #       - ./grafana/data/:/etc/grafana/provisioning/datasources/
  #       - ./grafana/dash/:/etc/grafana/provisioning/dashboards/
  #   links:
  #     - prometheus
  #   ports:
  #     - 3000:3000
